# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureActuelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degres', models.FloatField(default=-10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'ordering': ['date_ajout'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemperatureLac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degres', models.FloatField(default=-10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'ordering': ['date_ajout'],
                'abstract': False,
            },
        ),
    ]
